api/urls.py
from django.urls import path
from .views import *


app_name = "api"


urlpatterns = [
    path("descricao_rel/descricao", TenantDocumentViewSet.as_view({"get": "list"})),

]

avaliacao/urls.py
from django.urls import path

from api.views import TenantDocumentViewSet, DescricaoList
from .views import *

app_name = "avaliacao"


urlpatterns = [
    path("avaliacao_list/", AvaliacaoListView.as_view(), name="avaliacao-list"),
    path("avaliacao/create/", AvaliacaoCreateView.as_view(), name="avaliacao-create"),
    path("avaliacao/createmodelo/<int:pk>", AvaliacaoModeloCreateView.as_view(), name="avaliacao-modelo-create"),
    path("avaliacao/update/<int:pk>", AvaliacaoUpdateView.as_view(), name="avaliacao-update"),
    path("avaliacao/delete/<int:pk>", AvaliacaoDeleteView.as_view(), name="avaliacao-delete"),
    path('ajax/load-areas/', load_areas, name='ajax_load_areas'),
    path('ajax/load-sub_familias/', load_sub_familias, name='ajax_load_sub_familias'),
    path('ajax/load1-levels1/', load1_levels1, name='ajax_load1_levels1'),
    path('ajax/load1-levels2/', load1_levels2, name='ajax_load1_levels2'),
    path('ajax/load1-levels3/', load1_levels3, name='ajax_load1_levels3'),
    path('ajax/load1-levels5/', load1_levels5, name='ajax_load1_levels5'),
    path('ajax/load1-levels7/', load1_levels7, name='ajax_load1_levels7'),
    path('ajax/load1-levels8/', load1_levels8, name='ajax_load1_levels8'),
    path('ajax/load-levels1/', load_levels1, name='ajax_load_levels1'),
    path('ajax/load-levels2/', load_levels2, name='ajax_load_levels2'),
    path('ajax/load-levels3/', load_levels3, name='ajax_load_levels3'),
    path('ajax/load-levels4/', load_levels4, name='ajax_load_levels4'),
    path('ajax/load-levels5/', load_levels5, name='ajax_load_levels5'),
    path('ajax/load-levels6/', load_levels6, name='ajax_load_levels6'),
    path('ajax/load-levels7/', load_levels7, name='ajax_load_levels7'),
    path('ajax/load-levels8/', load_levels8, name='ajax_load_levels8'),
    path('ajax/load-grade/', load_grade, name='ajax_load_grade'),
    path('ajax/load-detalhe/', load_detalhe, name='ajax_load_detalhe'),
    path('ajax/load-alteracao/', load_alteracao, name='ajax_load_alteracao'),
    path('ajax/load-exclusao/', load_exclusao, name='ajax_load_exclusao'),
    path("avaliacao-manual", mostra_pdf, name="avaliacao-manual"),
    path("avaliacao_rel_list/", AvaliacaoRelListView.as_view(), name="avaliacao-rel-list"),
    path("avaliacao_pdf/<int:pk>", AvaliacaoPdfListView.as_view(), name="avaliacao-pdf-list"),
    path("avaliacao_excel/", export_users_csv, name="avaliacao-excel-list"),
    path("avaliacao_excel/matriz", export_matriz_csv, name="avaliacao-excel-matriz"),
    path("avaliacao_rel_list_matriz/", AvaliacaoRelMatrizListView.as_view(), name="avaliacao-rel-list-matriz"),
    path("avaliacao_rel_list_hierarquica/", AvaliacaoRelHierarquicaListView.as_view(),
         name="avaliacao-rel-list-hierarquica"),

    path("avaliacao/<int:pk>", AvaliacaoPdfDetailView.as_view(), name="avaliacao-pdf"),


]

bluebox/urls.py
import django.views.static
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from user_account.views import *
from django.contrib.auth import views as auth_views
from django.urls import re_path


admin.site.site_header = " "
admin.site.index_title = "Administração BlueBox21"
#admin.site.site_title = "BlueBox21"-->


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', logar_usuario, name="logar_usuario"),
    path('logar_usuario', logar_usuario, name="logar_usuario"),
    path('index.html', index,name="index"),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_set.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="set_password.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"), name="password_reset_complete"),
    re_path(r"person/", include("person.urls")),
    re_path(r"customuser/", include("user_account.urls")),
    re_path(r"diretoria/", include("master.urls")),
    re_path(r"area/", include("master.urls")),
    re_path(r"tenant/", include("tenants.urls")),
    re_path(r"admin_descricao/", include("admin_descricao.urls")),
    re_path(r"descricao/", include("descricao.urls")),
    re_path(r"avaliacao/", include("avaliacao.urls")),
    re_path(r"api/", include("api.urls")),
]

avaliacao/views.py
import csv
import os

from django.db.models import ProtectedError
from django.http import FileResponse, HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse_lazy
from django.views.generic import DeleteView, CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

import avaliacao
from admin_avaliacao.models import Niveis, Combinacoes
from descricao.models import Descricao
from master.models import Diretoria
from report.mixins import PdfResponseMixin
from tenants.utils import tenant_from_request, user_from_request

from .models import Avaliacao, Area, SubFamilias, Superior
from .forms import AvaliacaoForm, AvaliacaoModeloForm
from tenants.models import Tenant

from django.shortcuts import render, redirect

from io import BytesIO

import xlsxwriter
from django.http import HttpResponse

from django.db.models.deletion import ProtectedError
import json


from django.contrib import messages


class AvaliacaoDetailView(LoginRequiredMixin, DetailView):
    model = Avaliacao
    context_object_name = "avaliacao"


class AvaliacaoListView(LoginRequiredMixin, ListView):
    model = Avaliacao
    context_object_name = "avaliacao"

    def get_queryset(self):
        tenant_id = tenant_from_request(self.request)
        return super().get_queryset().filter(tenant_id=tenant_id).all()


class AvaliacaoDeleteView(LoginRequiredMixin, DeleteView):

    model = Avaliacao
    context_object_name = "avaliacao"
    success_url = reverse_lazy("avaliacao:avaliacao-list")

    def form_valid(self, form):
        success_url = self.get_success_url()

        idsuper=self.object.id
        # Deleta da tabela de superior imediato
        super = Superior.objects.filter(evaluation_id=idsuper)
        super.delete()

        self.object.delete()
        return HttpResponseRedirect(success_url)


class AvaliacaoCreateView(LoginRequiredMixin, CreateView):
    model = Avaliacao
    form_class = AvaliacaoForm
    success_url = reverse_lazy("avaliacao:avaliacao-list")

    def get_initial(self, *args, **kwargs):
        initial = super(AvaliacaoCreateView, self).get_initial(**kwargs)
        tenant_id = tenant_from_request(self.request)

        empresa = Tenant.objects.filter(id=tenant_id).first()
        if empresa:
            initial['origin'] = empresa.origin
            initial['governanca'] = empresa.governanca
            initial['company'] = empresa.company
            initial['size'] = empresa.size_id

        # avaliacao = Avaliacao.objects.filter(tenant_id=tenant_id, ceo=True).first()
        # if avaliacao:
        #     initial['ceo'] = False
        # else:
        #     initial['ceo'] = True

        return initial

        # avaliacao = Avaliacao.objects.filter(tenant_id=tenant_id).first()
        # if avaliacao:
        #     initial['title_super'] = avaliacao.title
        # return initial

    # Forçar o preenchimento do tenant_id com o tenant_id do usuario logado
    def form_valid(self, form):
        tenant_id = tenant_from_request(self.request)
        form.instance.tenant_id = tenant_id
        user_id = user_from_request(self.request)
        form.instance.user_id = user_id
        avaliacao = Avaliacao.objects.filter(tenant_id=tenant_id, ceo=True).first()
        if avaliacao:
            form.instance.ceo = False
        else:
            form.instance.ceo = True

        self.object = form.save()
        # Insere na tabela superiror imediado a avaliação cadastrada.
        Superior.objects.create(title=form.instance.title, tenant_id=tenant_id, evaluation_id=form.instance.id)

        return super(AvaliacaoCreateView, self).form_valid(form)

    # pegar o tenant do usuario logado para filtrar a dropdonw
    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(AvaliacaoCreateView, self).get_form_kwargs()
        tenant_id = tenant_from_request(self.request)
        kwargs['tenant_id'] = tenant_id
        return kwargs


class AvaliacaoModeloCreateView(LoginRequiredMixin, CreateView):
    model = Avaliacao
    form_class = AvaliacaoModeloForm
    success_url = reverse_lazy("avaliacao:avaliacao-list")

    def get_initial(self, *args, **kwargs):
        initial = super(AvaliacaoModeloCreateView, self).get_initial(**kwargs)
        tenant_id = tenant_from_request(self.request)

        empresa = Tenant.objects.filter(id=tenant_id).first()
        if empresa:
            initial['origin'] = empresa.origin
            initial['governanca'] = empresa.governanca
            initial['company'] = empresa.company
            initial['size'] = empresa.size

        descricao = Descricao.objects.filter(id=self.kwargs.get("pk")).first()
        if descricao:
            initial['title'] = descricao.title
            initial['board'] = descricao.board
            initial['area'] = descricao.area
            initial['family'] = descricao.family
            initial['sub_familia'] = descricao.sub_familia
            initial['formation'] = descricao.formation
            initial['manage_team'] = descricao.manage_team
            initial['description'] = descricao.id
        # avaliacao = Avaliacao.objects.filter(tenant_id=tenant_id, ceo=True).first()
        # if avaliacao:
        #     initial['ceo'] = False
        # else:
        #     initial['ceo'] = True

        return initial

    # Forçar o preenchimento do tenant_id com o tenant_id do usuario logado
    def form_valid(self, form):
        tenant_id = tenant_from_request(self.request)
        form.instance.tenant_id = tenant_id
        user_id = user_from_request(self.request)
        form.instance.user_id = user_id
        avaliacao = Avaliacao.objects.filter(tenant_id=tenant_id, ceo=True).first()
        if avaliacao:
            form.instance.ceo = False
        else:
            form.instance.ceo = True


        self.object = form.save()
        # Insere na tabela superior imediado a avaliação cadastrada.
        Superior.objects.create(title=form.instance.title, tenant_id=tenant_id, evaluation_id=form.instance.id)

        return super(AvaliacaoModeloCreateView, self).form_valid(form)

    # pegar o tenant do usuario logado para filtrar a dropdonw
    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(AvaliacaoModeloCreateView, self).get_form_kwargs()
        tenant_id = tenant_from_request(self.request)
        kwargs['tenant_id'] = tenant_id
        return kwargs


class AvaliacaoUpdateView(LoginRequiredMixin, UpdateView):
    model = Avaliacao
    form_class = AvaliacaoForm
    success_url = reverse_lazy("avaliacao:avaliacao-list")

    def get_initial(self, *args, **kwargs):
        initial = super(AvaliacaoUpdateView, self).get_initial(**kwargs)
        initial['level1'] = None
        initial['level2'] = None
        initial['level3'] = None
        initial['level4'] = None
        initial['level5'] = None
        initial['level6'] = None
        initial['level7'] = None
        initial['level8'] = None
        initial['grade'] = None
        return initial


        # pegar o tenant do usuario logado para filtrar a dropdonw
    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(AvaliacaoUpdateView, self).get_form_kwargs()
        tenant_id = tenant_from_request(self.request)
        kwargs['tenant_id'] = tenant_id
        kwargs['id'] = self.request.GET.get('pk')
        return kwargs


    # Forçar o preenchimento do tenant_id com o tenant_id do usuario logado
    def form_valid(self, form):
        tenant_id = tenant_from_request(self.request)
        id = form.instance.id
        avaliacao = Avaliacao.objects.filter(tenant_id=tenant_id, ceo=True).first()
        if avaliacao.id == id:
            form.instance.ceo = True
        else:
            form.instance.ceo = False

        self.object = form.save()

        return super(AvaliacaoUpdateView, self).form_valid(form)



class AvaliacaoPdfDetailView(PdfResponseMixin, DetailView):
    model = Avaliacao
    context_object_name = 'avaliacao'

class AvaliacaoRelListView(LoginRequiredMixin, ListView):
    template_name = 'avaliacao/avaliacao_rel_list.html'
    model = Avaliacao
    context_object_name = "avaliacao"

    def get_queryset(self):
        tenant_id = tenant_from_request(self.request)
        return super().get_queryset().filter(tenant_id=tenant_id).all()


class AvaliacaoRelMatrizListView(LoginRequiredMixin, ListView):
    template_name = 'avaliacao/avaliacao_rel_list_matriz.html'
    model = Avaliacao
    context_object_name = "avaliacoes"

    def get_queryset(self):
        tenant_id = tenant_from_request(self.request)
        return super().get_queryset().filter(tenant_id=tenant_id).all()

    def get_context_data(self, **kwargs):
        context = super(AvaliacaoRelMatrizListView, self).get_context_data(**kwargs)
        tenant_id = tenant_from_request(self.request)
        context['diretorias'] = Diretoria.objects.filter(tenant_id=tenant_id)
        return context


class AvaliacaoRelHierarquicaListView(LoginRequiredMixin, ListView):
    template_name = 'avaliacao/avaliacao_rel_list_hierarquica.html'
    model = Avaliacao
    context_object_name = "avaliacoes"

    def get_queryset(self):
        tenant_id = tenant_from_request(self.request)
        return super().get_queryset().filter(tenant_id=tenant_id).all()


def mostra_pdf(request):
    filepath = os.path.join('static', '/home/cristiano/bluebox/staticfiles/pdf/manual_avaliacao.pdf')
    return FileResponse(open(filepath, 'rb'), content_type='application/pdf')


# Chamado no batao de gerar pdf do relatorio de acompanhamento
class AvaliacaoPdfListView(PdfResponseMixin, ListView):
    template_name = 'avaliacao/avaliacao_pdf_list.html'
    model = Avaliacao
    context_object_name = "avaliacao"

    def get_queryset(self):
        tenant_id = tenant_from_request(self.request)
        return self.model.objects.filter(tenant_id=tenant_id).all()

avaliacao/templates/avaliacao/area_dropdown_list_options.html
<option value="">---------</option>
{% for area in areas %}
<option value="{{ area.id }}">{{ area.name }}</option>
{% endfor %}

avaliacao/templates/avaliacao/avaliacao_confirm_delete.html
{% extends 'base.html' %}

{% block conteudo_painel %}
    <h2>Exclusão da Avaliação</h2>
    <br>
    <form method="post">{% csrf_token %}
        <p>Tem certeza que deseja apagar?</p>
        <button type="submit" class="btn btn-danger" data-toggle="tooltip" data-placement="top"
                title="Cuidado! Essa operação não pode ser desfeita!">Confirmar
        </button>
        <a href="{% url 'avaliacao:avaliacao-list' %}"><button type="button" class="btn btn-secondary">Cancelar</button></a>
    </form>
{% endblock %}

avaliacao/templates/avaliacao/avaliacao_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo_painel %}

{% endblock titulo_painel %}

{% block conteudo_painel %}
<form method="post" enctype="multipart/form-data" xmlns="http://www.w3.org/1999/html"
      xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html"
      xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">{% csrf_token %}

    <table border="1" >
        <thead>
            <tr>
                <th> <img align = center height=50 src="/logo_v.jpg" /> </th>
                <th colspan="4" style="height: 80px; font-size:180%">  Avaliação - {{avaliacao.title}} </th>
            </tr>
        </thead>
    </table>
    </br>
    <table border=1>
        <tr>
            <th style="height: 30px; font-size:120%" align="center" valign="bottom" bgcolor="silver">Identificação</th>
        </tr>
        <tr>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">Titulo do Cargo: {{avaliacao.title}}</th>
        </tr>
        <tr>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">Superior: {{avaliacao.title_super}} </th>
        </tr>
        <tr>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">Gerente: {{avaliacao.manage_team}}</th>
        </tr>
        <tr>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">Área: {{avaliacao.board}}</th>
        </tr>
        <tr>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">Subárea: {{avaliacao.area}}</th>
        </tr>
        <tr>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">Familia de Cargo: {{avaliacao.family}}</th>
        </tr>
        <tr>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">Subfámilia de Cargo: {{avaliacao.sub_familia}}</th>
        </tr>
    </table>
        </br>
        </br>
    <table border=1>
        <tr>
            <th colspan="2" style="height: 30px; font-size:120%" align="center" valign="bottom" bgcolor="silver">Fatores</th>
            <th colspan="2" style="height: 30px; font-size:120%" align="center" valign="bottom" bgcolor="silver">Níveis</th>
        </tr>
    </table>
    <table border=1>
        <tr>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.factor1}}</th>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.level1}}</th>
        </tr>
        <tr>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.factor2}}</th>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.level2}}</th>
        </tr>
        <tr>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.factor3}}</th>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.level3}}</th>
        </tr>
        <tr>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.factor4}}</th>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.level4}}</th>
        </tr>
        <tr>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.factor5}}</th>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.level5}}</th>
        </tr>
        <tr>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.factor6}}</th>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.level6}}</th>
        </tr>
        <tr>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.factor7}}</th>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.level7}}</th>
        </tr>
        <tr>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.factor8}}</th>
            <th style="height: 25px; font-size:100%" align="left" valign="bottom">{{avaliacao.level8}}</th>
        </tr>
    </table>
    </br>
    </br>
    </br>
    </br>
    <table border=1>
        <tr>
            <th style="height: 30px; font-size:120%" align="center" valign="bottom" bgcolor="silver">Resultado</th>
        </tr>
        <tr>
            <th style="height: 25px; font-size:100%" align="center" valign="bottom">Grade: {{avaliacao.grade}}</th>
        </tr>
    </table>
</form>
{% endblock %}

avaliacao/templates/avaliacao/avaliacao_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo_painel %}
    <strong>Cargos Avaliados</strong>
{% endblock titulo_painel %}

{% block conteudo_painel %}

    <a id="add-link" href="{% url 'avaliacao:avaliacao-create' %}">
        <div class="col-2 add-div">
            <i class="fas fa-plus"></i> Adicionar Avaliação de Cargo
        </div>
    </a>
    <br>

    <form method="post" enctype="multipart/form-data" id="avaliacaoForm"
          data-alteracao-url="{% url 'avaliacao:ajax_load_alteracao' %}"
          data-exclusao-url="{% url 'avaliacao:ajax_load_exclusao' %}">
        {% csrf_token %}

        <div class="row">
            <div class="col-md-12">
                <table id="table_id" class="display" align="center" style="width:100%">
                    <thead>
                        <tr>
                            <th>Cargo</th>
                            <th><center>Visualizar</center></th>
                            <th><center>Reavaliar</center></th>
                            <th><center>Excluir</center></th>
                        </tr>
                    </thead>
                    <tbody>
                    {%for avaliacao in object_list %}
                        <tr>
                            <td>{{avaliacao.title}}</td>

                            <td><a href="{% url 'avaliacao:avaliacao-pdf' avaliacao.id %}"><center><i class="fa fa-eye"></i></center></a></td>

                            <td><center><button onclick="alteracao({{avaliacao.id}})" type="button" type="button"
                                                class="btn btn-primary "><i class="fa fa-edit"></i></button></center></td>

                            <td><center><button onclick="exclusao({{avaliacao.id}})" type="button" type="button"
                                                class="btn btn-primary "><i class="far fa-trash-alt"></i></button></center></td>
                        </tr>
                     {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <br>
         <a href="/index.html"><button type="button" class="btn btn-secondary">Voltar</button></a>
    </form>

{% endblock conteudo_painel %}

{% block js %}
<script>

$(document).ready( function () {
    $('#table_id').DataTable();
} );


function alteracao(id) {
    var url = $("#avaliacaoForm").attr("data-alteracao-url");
    var url1 = $("#avaliacaoForm").attr("data-update-url");

    $.ajax({                       // initialize an AJAX request
        url: url,               // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
              'id': id       // add the country id to the GET parameters,      // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          if (data != "") {
            var retorno = confirm(data);
            if (retorno == true)
            {
                window.location = "//bluebox21-a62c5eb102e8.herokuapp.com/avaliacao/avaliacao/update/" + id;
<!--                    window.location = "http://127.0.0.1:8000/avaliacao/avaliacao/update/" + id;-->
            }

          } else {
                window.location = "///bluebox21-a62c5eb102e8.herokuapp.com/avaliacao/avaliacao/update/" + id;
<!--               window.location = "http://127.0.0.1:8000/avaliacao/avaliacao/update/" + id;-->
          }
        }
    });

}


function exclusao(id) {
    var url = $("#avaliacaoForm").attr("data-exclusao-url");

    $.ajax({                       // initialize an AJAX request
        url: url,               // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
              'id': id       // add the country id to the GET parameters,      // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
            if (data != "") {
                alert(data);
            }
            else {
<!--                window.location = "http://127.0.0.1:8000/avaliacao/avaliacao/delete/" + id;-->
                window.location = "https://bluebox21-a62c5eb102e8.herokuapp.com/avaliacao/avaliacao/delete/" + id;

            }
        }
    });
}


</script>
{% endblock js %}

avaliacao/templates/avaliacao/avaliacao_rel_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo_painel %}
    Relatório - Avaliações Detalhadas
{% endblock titulo_painel %}

{% block conteudo_painel %}

    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12">
                <table id="table_id" class="display"  style="width:100%">

                    <thead>
                        <tr align="left">
                            <th><font size=1>Cargo</font></th>
<!--                            <th><font size=1>Diretoria</font></th>-->
<!--                            <th><font size=1>Area</font></th>-->
                            <th><font size=1>Grade</font></th>
                            <th><font size=1>Nivel</font></th>
                            <th><font size=1>Formação</font></th>
                            <th><font size=1>Escopo</font></th>
                            <th><font size=1>Abrangência</font></th>
                            <th><font size=1>Contribuição</font></th>
                            <th><font size=1>Gestão</font></th>
                            <th><font size=1>Liderança</font></th>
                            <th><font size=1>Comunicação</font></th>
                        </tr>
                    </thead>

                    <tbody>
                    {%for avaliacao in object_list %}
                        <tr align="left">

                            <td><font size=1>{{avaliacao.title}}</font></td>
<!--                            <td><font size=1>{{avaliacao.board}}</font></td>-->
<!--                            <td><font size=1>{{avaliacao.area}}</font></td>-->
                            <td><font size=1>{{avaliacao.grade}}</font></td>
                            <td><font size=1>{{avaliacao.level1}}</font></td>
                            <td><font size=1>{{avaliacao.level2}}</font></td>
                            <td><font size=1>{{avaliacao.level3}}</font></td>
                            <td><font size=1>{{avaliacao.level4}}</font></td>
                            <td><font size=1>{{avaliacao.level5}}</font></td>
                            <td><font size=1>{{avaliacao.level6}}</font></td>
                            <td><font size=1>{{avaliacao.level7}}</font></td>
                            <td><font size=1>{{avaliacao.level8}}</font></td>

                        </tr>
                     {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <br>
         <a href="/index.html"><button type="button" class="btn btn-secondary">Voltar</button></a>
         <a href="{% url 'avaliacao:avaliacao-pdf-list' 1 %}"><button type="button" class="btn btn-success">Gerar PDF</button></a>
         <a href="{% url 'avaliacao:avaliacao-excel-list' %}"><button type="button" class="btn btn-success">Gerar Excel</button></a>
    </form>

{% endblock conteudo_painel %}

{% block js %}
<script>
    $(document).ready( function () {
        $('#table_id').DataTable();
    } );
</script>
{% endblock js %}

avaliacao/templates/avaliacao/grade_list_options.html
<!--<option value="">-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>-->
{% for combinacao in combinacoes %}
<option value="{{ combinacao.id }}">{{ combinacao.grade }}</option>
{% endfor %}

avaliacao/templates/avaliacao/level1_dropdown_list_options.html
<option value="">---------</option>
{% for level in levels %}
    <option value="{{ level.id }}" value="{{ level.name }}">{{ level.code }} - {{ level.name }}</option>
{% endfor %}

avaliacao/templates/avaliacao/niveis_detalhe.html
{% for detalhe in detalhes %}
    {{ detalhe.name }}.

    {{ detalhe.detail }}
{% endfor %}

avaliacao/templates/avaliacao/sub_familia_dropdown_list_options.html
<option value="">---------</option>
{% for sub_familia in sub_familias %}
<option value="{{ sub_familia.id }}">{{ sub_familia.name }}</option>
{% endfor %}

avaliacao/templates/avaliacao/title_super_dropdown_list_options.html
<option value="">---------</option>
{% for superior in superiores %}
<option value="{{ superior.id }}">{{ superior.title }}</option>
{% endfor %}