api/urls.py
from django.urls import path
from .views import *


app_name = "api"


urlpatterns = [
    path("descricao_rel/descricao", TenantDocumentViewSet.as_view({"get": "list"})),

]

avaliacao/urls.py
from django.urls import path

from api.views import TenantDocumentViewSet, DescricaoList
from .views import *

app_name = "avaliacao"


urlpatterns = [
    path("avaliacao_list/", AvaliacaoListView.as_view(), name="avaliacao-list"),
    path("avaliacao/create/", AvaliacaoCreateView.as_view(), name="avaliacao-create"),
    path("avaliacao/createmodelo/<int:pk>", AvaliacaoModeloCreateView.as_view(), name="avaliacao-modelo-create"),
    path("avaliacao/update/<int:pk>", AvaliacaoUpdateView.as_view(), name="avaliacao-update"),
    path("avaliacao/delete/<int:pk>", AvaliacaoDeleteView.as_view(), name="avaliacao-delete"),
    path('ajax/load-areas/', load_areas, name='ajax_load_areas'),
    path('ajax/load-sub_familias/', load_sub_familias, name='ajax_load_sub_familias'),
    path('ajax/load1-levels1/', load1_levels1, name='ajax_load1_levels1'),
    path('ajax/load1-levels2/', load1_levels2, name='ajax_load1_levels2'),
    path('ajax/load1-levels3/', load1_levels3, name='ajax_load1_levels3'),
    path('ajax/load1-levels5/', load1_levels5, name='ajax_load1_levels5'),
    path('ajax/load1-levels7/', load1_levels7, name='ajax_load1_levels7'),
    path('ajax/load1-levels8/', load1_levels8, name='ajax_load1_levels8'),
    path('ajax/load-levels1/', load_levels1, name='ajax_load_levels1'),
    path('ajax/load-levels2/', load_levels2, name='ajax_load_levels2'),
    path('ajax/load-levels3/', load_levels3, name='ajax_load_levels3'),
    path('ajax/load-levels4/', load_levels4, name='ajax_load_levels4'),
    path('ajax/load-levels5/', load_levels5, name='ajax_load_levels5'),
    path('ajax/load-levels6/', load_levels6, name='ajax_load_levels6'),
    path('ajax/load-levels7/', load_levels7, name='ajax_load_levels7'),
    path('ajax/load-levels8/', load_levels8, name='ajax_load_levels8'),
    path('ajax/load-grade/', load_grade, name='ajax_load_grade'),
    path('ajax/load-detalhe/', load_detalhe, name='ajax_load_detalhe'),
    path('ajax/load-alteracao/', load_alteracao, name='ajax_load_alteracao'),
    path('ajax/load-exclusao/', load_exclusao, name='ajax_load_exclusao'),
    path("avaliacao-manual", mostra_pdf, name="avaliacao-manual"),
    path("avaliacao_rel_list/", AvaliacaoRelListView.as_view(), name="avaliacao-rel-list"),
    path("avaliacao_pdf/<int:pk>", AvaliacaoPdfListView.as_view(), name="avaliacao-pdf-list"),
    path("avaliacao_excel/", export_users_csv, name="avaliacao-excel-list"),
    path("avaliacao_excel/matriz", export_matriz_csv, name="avaliacao-excel-matriz"),
    path("avaliacao_rel_list_matriz/", AvaliacaoRelMatrizListView.as_view(), name="avaliacao-rel-list-matriz"),
    path("avaliacao_rel_list_hierarquica/", AvaliacaoRelHierarquicaListView.as_view(),
         name="avaliacao-rel-list-hierarquica"),

    path("avaliacao/<int:pk>", AvaliacaoPdfDetailView.as_view(), name="avaliacao-pdf"),


]

bluebox/urls.py
import django.views.static
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from user_account.views import *
from django.contrib.auth import views as auth_views
from django.urls import re_path


admin.site.site_header = " "
admin.site.index_title = "Administração BlueBox21"
#admin.site.site_title = "BlueBox21"-->


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', logar_usuario, name="logar_usuario"),
    path('logar_usuario', logar_usuario, name="logar_usuario"),
    path('index.html', index,name="index"),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_set.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="set_password.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"), name="password_reset_complete"),
    re_path(r"person/", include("person.urls")),
    re_path(r"customuser/", include("user_account.urls")),
    re_path(r"diretoria/", include("master.urls")),
    re_path(r"area/", include("master.urls")),
    re_path(r"tenant/", include("tenants.urls")),
    re_path(r"admin_descricao/", include("admin_descricao.urls")),
    re_path(r"descricao/", include("descricao.urls")),
    re_path(r"avaliacao/", include("avaliacao.urls")),
    re_path(r"api/", include("api.urls")),
]

descricao/urls.py
from django.urls import path

from api.views import TenantDocumentViewSet, DescricaoList
from .views import *

app_name = "descricao"


urlpatterns = [
    path("descricao_list/", DescricaoListView.as_view(), name="descricao-list"),
    path("descricao/create/", DescricaoCreateView.as_view(), name="descricao-create"),
    path("descricao/importar_dados/", ImportarDadosView.as_view(), name="descricao-create-lote"),
    path("descricao/createmodelo/<int:pk>", DescricaoModeloCreateView.as_view(), name="descricao-modelo-create"),
    path("descricao/update/<int:pk>", DescricaoUpdateView.as_view(), name="descricao-update"),
    path("descricao/delete/<int:pk>", DescricaoDeleteView.as_view(), name="descricao-delete"),
    path('ajax/load-areas/', load_areas, name='ajax_load_areas'),
    path('ajax/load-sub_familias/', load_sub_familias, name='ajax_load_sub_familias'),
    path("descricao/<int:pk>", DescricaoPdfDetailView.as_view(), name="descricao-pdf"),

    path("descricao/email/<str:title>/<str:email>", envia_email_acompanhamento, name="descricao-email"),

    path("descricao_rel_list/", DescricaoRelListView.as_view(), name="descricao-rel-list"),
    path("descricao_pdf/<int:pk>", DescricaoPdfListView.as_view(), name="descricao-pdf-list"),
    path("descricao_excel/", export_users_csv, name="descricao-excel-list"),
    # path("descricao_rel/descricao", TenantDocumentViewSet.as_view({"get": "list"}), name="descricao-rel"),
    path("descricao-manual", mostra_pdf, name="descricao-manual"),
    path("descricao_rel/descricao", DescricaoList.as_view({"get": "list"}), name="descricao-rel"),
    path("descricaomodelo_list/", DescricaomodeloListView.as_view(), name="descricaomodelo-list"),
    # path("tenants/<int:pk>/documents/", TenantDocumentViewSet.as_view({"get": "list"})),
    # path("document/", DocumentListView.as_view(), name="document-list"),
    path("descricao_list_aprovador/", DescricaoAprovadorListView.as_view(), name="descricao-list-aprovador"),
    path("descricao/update/aprovador/<int:pk>", DescricaoAprovadorUpdateView.as_view(), name="descricao-update-aprovador"),
    path("descricao_list_aprovacao/", DescricaoAprovacaoListView.as_view(), name="descricao-list-aprovacao"),
    path("descricao/update/aprovacao/<int:pk>", DescricaoAprovacaoUpdateView.as_view(), name="descricao-update-aprovacao"),
    path("descricao_aprovacao/<int:pk>", envia_aprovacao, name="descricao-aprovacao"),
    path("descricao_reprovacao/<int:pk>", envia_reprovacao, name="descricao-reprovacao"),
    path("descricao_list_aprovacao_final/", DescricaoAprovacaoFinalListView.as_view(), name="descricao-list-aprovacao-final"),
    path("descricao/update/aprovacao_final/<int:pk>", DescricaoAprovacaoFinalUpdateView.as_view(),
         name="descricao-update-aprovacao-final"),
    path('ajax/load-ia/', load_ia, name='ajax_load_ia'),
]

descricao/models.py
from django.db import models

from admin_descricao.models import Formacao, Areas, Especializacoes, Experiencias, Habilitacoes, Idiomas, Status, \
    Gerencia, Proficiencias, AreasEspecializacoes, Niveis
from master.models import Diretoria, Area
from admin_avaliacao.models import Familias, SubFamilias, Fatores
from user_account.models import CustomUser

from tenants.models import TenantAwareModel

from admin_geral.models import Sector


class Descricao(TenantAwareModel):

    title = models.CharField(max_length=255, verbose_name='Título do Cargo', null=False, default="", help_text='',)
    cbo = models.CharField(null=True,max_length=255, verbose_name='CBO', blank=True, default="")
    function = models.CharField(null=True,max_length=255, verbose_name='Função', blank=True, default="")
    summary_goal = models.TextField(max_length=1000, verbose_name='Missão do Cargo', null=True, default="")
    responsibility = models.TextField(max_length=1000, verbose_name='Principais Responsabilidades', null=True, default="")
    formation = models.ForeignKey(Formacao, on_delete=models.PROTECT, related_name='formation', verbose_name='Grau de Escolaridade Mínimo', null=True, blank=True, default="")
    areas = models.ForeignKey(Areas, on_delete=models.PROTECT, verbose_name='Área de Formação Obrigatória 1', related_name='Area_1',
                              blank=True, null=True)
    areas2 = models.ForeignKey(Areas, on_delete=models.PROTECT, verbose_name='Área de Formação Obrigatória 2', related_name='Area_2',
                               blank=True, null=True)
    areas3 = models.ForeignKey(Areas, on_delete=models.PROTECT, verbose_name='Área de Formação Obrigatória 3', related_name='Area_3',
                               blank=True, null=True)
    areas4 = models.ForeignKey(Areas, on_delete=models.PROTECT, verbose_name='Área de Formação Obrigatória 4', related_name='Area_4',
                               blank=True, null=True)
    formation_desired = models.ForeignKey(Formacao, null=True, on_delete=models.PROTECT, related_name='formation_desired1', verbose_name='Grau de Escolaridade Desejável', default="")
    areas_desired = models.ForeignKey(Areas, on_delete=models.PROTECT, related_name='areas_desired_1',
                                      verbose_name='Area de Formação Desejada 1',blank=True, null=True, default="")
    areas_desired2 = models.ForeignKey(Areas, on_delete=models.PROTECT, related_name='areas_desired_2',
                                      verbose_name='Area de Formação Desejada 2', blank=True, null=True, default="")
    areas_desired3 = models.ForeignKey(Areas, on_delete=models.PROTECT, related_name='areas_desired_3',
                                      verbose_name='Area de Formação Desejada 3', blank=True, null=True, default="")
    areas_desired4 = models.ForeignKey(Areas, on_delete=models.PROTECT, related_name='areas_desired_4',
                                      verbose_name='Area de Formação Desejada 4', blank=True, null=True, default="")
    specialization = models.ForeignKey(Especializacoes, on_delete=models.PROTECT, verbose_name='Formação Complementar', blank=True, null=True, default="")
    area_specialization = models.ForeignKey(Areas, on_delete=models.PROTECT, verbose_name='Área de Formação Complementar 1',
                                related_name='area_specialization_1',
                                blank=True, null=True)
    area_specialization2 = models.ForeignKey(Areas, on_delete=models.PROTECT, verbose_name='Área de Formação Complementar 2',
                               related_name='area_specialization_2',
                               blank=True, null=True)
    area_specialization3 = models.ForeignKey(Areas, on_delete=models.PROTECT, verbose_name='Área de Formação Complementar 3',
                               related_name='area_specialization_3',
                               blank=True, null=True)
    area_specialization4 = models.ForeignKey(Areas, on_delete=models.PROTECT, verbose_name='Área de Formação Complementar 4',
                               related_name='area_specialization_4',
                               blank=True, null=True)
    experience = models.ForeignKey(Experiencias, on_delete=models.PROTECT, verbose_name='Experiencia')
    qualification = models.ForeignKey(Habilitacoes, on_delete=models.PROTECT, related_name='Habilitacao_1',
                                      verbose_name='Habilitação/Certificação Obrigatória 1', null=True, blank=True)
    qualification2 = models.ForeignKey(Habilitacoes, on_delete=models.PROTECT, related_name='Habilitacao_2',
                                       verbose_name='Habilitação/Certificação Obrigatória 2', null=True, blank=True)
    qualification3 = models.ForeignKey(Habilitacoes, on_delete=models.PROTECT, related_name='Habilitacao_3',
                                       verbose_name='Habilitação/Certificação Obrigatória 3', null=True, blank=True)
    is_active = models.BooleanField(default=False, verbose_name='Ativo')
    board = models.ForeignKey(Diretoria, null=True, on_delete=models.PROTECT, verbose_name='Área')
    area = models.ForeignKey(Area, null=True, on_delete=models.PROTECT, verbose_name='Subárea')
    title_super = models.CharField(max_length=255, verbose_name='Título do Cargo do Superior Imediato',  null=True, default="")
    family = models.ForeignKey(Familias, null=True, blank=True, on_delete=models.PROTECT, verbose_name='Família do Cargo')
    sub_familia = models.ForeignKey(SubFamilias, null=True, blank=True, on_delete=models.PROTECT, verbose_name='SubFamília do Cargo')
    manage_team = models.ForeignKey(Gerencia, on_delete=models.PROTECT, verbose_name='Gestão de Equipe', related_name='gerencia')
    position_team = models.TextField(max_length=1000, verbose_name='Cargos da Equipe', blank=True, null=True, default="" )
    idioma = models.ForeignKey(Idiomas, null=True, blank=True, on_delete=models.PROTECT, verbose_name='Idioma 1',  related_name='idioma1')
    idioma2 = models.ForeignKey(Idiomas, null=True, blank=True, on_delete=models.PROTECT, verbose_name='Idioma 2', related_name='idioma2')
    idioma3 = models.ForeignKey(Idiomas, null=True, blank=True, on_delete=models.PROTECT, verbose_name='Idioma 3', related_name='idioma3')
    proficiency = models.ForeignKey(Proficiencias, null=True, blank=True, on_delete=models.PROTECT, verbose_name='Proficiência 1',  related_name='proficiencia1')
    proficiency2 = models.ForeignKey(Proficiencias, null=True, blank=True, on_delete=models.PROTECT,
                                    verbose_name='Proficiência 2',  related_name='proficiencia2')
    proficiency3 = models.ForeignKey(Proficiencias, null=True, blank=True, on_delete=models.PROTECT,
                                    verbose_name='Proficiência 3',  related_name='proficiencia3')
    knowledge = models.TextField(max_length=1000, verbose_name='Conhecimentos Específicos', blank=True, default="")
    information = models.TextField(max_length=1000, verbose_name='Outras Informações', blank=True, default="")
    approver = models.ForeignKey(CustomUser, null=True, blank=True, on_delete=models.PROTECT, verbose_name='Aprovador', related_name='approver')
    date_approval = models.DateTimeField(null=True, blank=True, verbose_name='Data de Aprovação')
    status = models.ForeignKey(Status, on_delete=models.PROTECT, verbose_name='Status', related_name='status')
    user_id = models.ForeignKey(CustomUser, null=True, blank=True, on_delete=models.PROTECT, verbose_name='Elaborador', related_name='user_id')
    date_conclusion = models.DateTimeField(null=True, blank=True, verbose_name='Data de Conclusao')
    is_active = models.BooleanField(default=True, verbose_name='Ativo')
    level = models.ForeignKey(Niveis, null=True, blank=True, on_delete=models.PROTECT, verbose_name='Nivel do Cargo')
    sector = models.ForeignKey(Sector, null=True, blank=True, on_delete=models.PROTECT, verbose_name='Setor de Atuação')

    def __str__(self):
        return f"{self.title}"

    class Meta:
        unique_together = ('title', 'tenant_id', 'is_active')
        verbose_name = 'Descricao'
        verbose_name_plural = 'Descricao'

descricao/templates/descricao/descricao_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo_painel %}
   Cadastro da Descrição de Cargos

{% endblock titulo_painel %}


{% block conteudo_painel %}
<form method="post" enctype="multipart/form-data" id="descricaoForm"
      data-areas-url="{% url 'descricao:ajax_load_areas' %}"
      data-sub_familias-url="{% url 'descricao:ajax_load_sub_familias' %}"
      data-ia-url="{% url 'descricao:ajax_load_ia' %}">{% csrf_token %}

    <font size=2>
        <div class="row">
            <div class="col-md-4">
                {{ form.title|as_crispy_field }}
                {# Here you print out any field error #}
                {% if field.errors %}
                    {% for error in field.errors %}
                        <p style="color: red;"> {{ error }} <p>
                     {% endfor %}
                {% endif %}
            </div>
            <div class="col-md-4">
                {{ form.function|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.status|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                {{ form.board|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.area|as_crispy_field }}
            </div><div class="col-md-4">
                {{ form.title_super|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                {{ form.family|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.sub_familia|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.level|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                {{ form.sector|as_crispy_field }}
            </div>
            <div class="col-md-4">
<!--                <center>-->
                    <br>
                    <button onclick="DescricaoIA()" type="button" class="btn btn-primary"><b>  Usar IA</b></button>
<!--                </center>-->
                <div class='loading'>
                    <img src='https://i.sstatic.net/fLkAW.gif' alt=''/>
                </div>

            </div>

        </div>
        <div class="row">
            <div class="col-md-4">
                {{ form.manage_team|as_crispy_field }}
            </div>
        </div>

        {{ form.position_team|as_crispy_field }}

<!--        <div class="row">-->
<!--            <div class="col-md-4">-->
        {{ form.summary_goal|as_crispy_field }}
<!--            </div>-->
<!--        </div>-->
<!--        <div class="row">-->
<!--            <div class="col-md-4">-->
        {{ form.responsibility|as_crispy_field }}
<!--            </div>-->
<!--        </div>-->
        <br>
        <div class="row">
            <div class="col-md-4">
                {{ form.formation|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.formation_desired|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.specialization|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                {{ form.areas|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.areas_desired|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.area_specialization|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                {{ form.areas2|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.areas_desired2|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.area_specialization2|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                {{ form.areas3|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.areas_desired3|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.area_specialization3|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                {{ form.areas4|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.areas_desired4|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.area_specialization4|as_crispy_field }}
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-4">
                {{ form.idioma|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.idioma2|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.idioma3|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                {{ form.proficiency|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.proficiency2|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.proficiency3|as_crispy_field }}
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
                {{ form.qualification|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.qualification2|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.qualification3|as_crispy_field }}
            </div>
        </div>
        <br>
<!--        <div class="row">-->
<!--            <div class="col-md-4">-->
        {{ form.knowledge|as_crispy_field }}
<!--            </div>-->
<!--        </div>-->
<!--        <div class="row">-->
<!--            <div class="col-md-4">-->
        {{ form.information|as_crispy_field }}
<!--            </div>-->
<!--        </div>-->
        <div class="row">
            <div class="col-md-4">
                {{ form.experience|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.cbo|as_crispy_field }}
            </div>
            <div class="col-md-4">
                {{ form.is_active|as_crispy_field }}
            </div>
<!--            <div class="col-md-4">-->
<!--                {{ form.approver|as_crispy_field }}-->
<!--            </div>-->
<!--            <div class="col-md-4">-->
<!--                {{ form.date_approval|as_crispy_field }}-->
<!--            </div>-->
        </div>
<!--        <br>-->
<!--        <div class="row">-->

<!--            <div class="col-md-4">-->
<!--                {{ form.cbo|as_crispy_field }}-->
<!--            </div>-->
<!--&lt;!&ndash;            <div class="col-md-4">&ndash;&gt;-->
<!--&lt;!&ndash;                {{ form.user_id|as_crispy_field }}&ndash;&gt;-->
<!--&lt;!&ndash;            </div>&ndash;&gt;-->
<!--            <div class="col-md-4">-->
<!--                {{ form.is_active|as_crispy_field }}-->
<!--            </div>-->
<!--        </div>-->
    </font>

    <br>

    <button type="submit" class="btn btn-success">Salvar</button>
    {% if descricao.id != null %}
        <a href="{% url 'descricao:descricao-aprovacao' descricao.id %}"><button type="button" class="btn btn-success">Finalizar/Aprovação</button></a>
    {% else %}
<!--        <button type="submit" class="btn btn-success" value="aprovado">Finalizar/Aprovação</button>-->
        <input class="btn btn-primary" type="submit" name="submit" value="Finalizar" />
    {% endif %}

    <a href="{% url 'descricao:descricao-list' %}"><button type="button" class="btn btn-secondary">Cancelar</button></a>

</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_board").change(function () {
      var url = $("#descricaoForm").attr("data-areas-url");  // get the url of the `load_cities` view
      var boardId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'board': boardId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_area").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });

    $("#id_family").change(function () {
      var url = $("#descricaoForm").attr("data-sub_familias-url");  // get the url of the `load_cities` view
      var familyId = $(this).val();  // get the selected country ID from the HTML input

      $.ajax({                       // initialize an AJAX request
        url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
        data: {
          'family': familyId       // add the country id to the GET parameters
        },
        success: function (data) {   // `data` is the return of the `load_cities` view function
          $("#id_sub_familia").html(data);  // replace the contents of the city input with the data that came from the server
        }
      });

    });

    function DescricaoIA() {                                   // Mostra descrição da IA
        var url = $("#descricaoForm").attr("data-ia-url");
        var title = $("#id_title").val();                        // Titulo
        var familyid = $("#id_family").val();                    // Familia
        var sub_familiaoid = $("#id_sub_familia").val();         // Sub Familia
        var levelid = $("#id_level").val();                      // Nivel
        var sectorid = $("#id_sector").val();                    // Setor
        var loading = $('.loading');                             // Ampulheta


        if ((title.trim().length == 0) || (familyid.trim().length == 0) || (sub_familiaoid.trim().length == 0) || (levelid.trim().length == 0) || (sectorid.trim().length == 0)) {
            alert('Para usar a IA, os campos: Título do Cargo, Família, Sub Família, Nivel do Cargo e Setor de Atuação devem ser preenchidos.');
            return false;

        }

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
              'title': title,      // add the country id to the GET parameters
              'family': familyid,        // add the country id to the GET parameters,      // add the country id to the GET parameters
              'sub_familia': sub_familiaoid,        // add the country id to the GET parameters,      // add the country id to the GET parameters
              'level': levelid,        // add the country id to the GET parameters,      // add the country id to the GET parameters
              'sector': sectorid,        // add the country id to the GET parameters,      // add the country id to the GET parameters
            },

            beforeSend: function(){
                loading.css('visibility', 'visible'); // exibe o div
            },

            complete: function(){
                loading.css('visibility', 'hidden'); // esconde o div
            },

            success: function (data) {   // `data` is the return of the `load_cities` view function

<!--                alert(data);-->
                data = data.split("|");

<!--                alert(data[3]);-->

                $('#summary_goal').html(data[0]);
                $('#responsibility').html(data[1]);
                $('#information').html(data[2]);

<!--                $("#id_manage_team").html(data[3]);-->
                $("#id_manage_team").val(Number(data[3]));
                $('#id_formation_desired').val(Number(data[4]));
                $('#id_specialization').val(Number(data[5]));
                $('#id_experience').val(Number(data[6]));
                $("#id_areas_desired").val(Number(data[7]));
                $("#id_qualification").val(Number(data[8]));

            }

       });
    }

</script>
{% endblock %}

descricao/templates/descricao/descricao_manual.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--<a <iframe src="'../pdf/manual_cargos.pdf'" width="600" height="780" style="border: none;"></iframe>-->

<a href='../pdf/manual_cargos.pdf'   target="_blank">pdf_001</a>
</body>
</html>

descricao/templates/descricao/ia_dropdown_list_options.html
{% for ia in ias %}
    {{ ia.missao }}|
    {{ ia.responsabilidades }}|
    {{ ia.competencias }}|
    {{ ia.equipe }}|
    {{ ia.escolaridade }}|
    {{ ia.complementar }}|
    {{ ia.experiencia }}|
    {{ ia.area_formacao }}|
    {{ ia.habilitacao }}|
{% endfor %}