api/urls.py
from django.urls import path
from .views import *


app_name = "api"


urlpatterns = [
    path("descricao_rel/descricao", TenantDocumentViewSet.as_view({"get": "list"})),

]

avaliacao/urls.py
from django.urls import path

from api.views import TenantDocumentViewSet, DescricaoList
from .views import *

app_name = "avaliacao"


urlpatterns = [
    path("avaliacao_list/", AvaliacaoListView.as_view(), name="avaliacao-list"),
    path("avaliacao/create/", AvaliacaoCreateView.as_view(), name="avaliacao-create"),
    path("avaliacao/createmodelo/<int:pk>", AvaliacaoModeloCreateView.as_view(), name="avaliacao-modelo-create"),
    path("avaliacao/update/<int:pk>", AvaliacaoUpdateView.as_view(), name="avaliacao-update"),
    path("avaliacao/delete/<int:pk>", AvaliacaoDeleteView.as_view(), name="avaliacao-delete"),
    path('ajax/load-areas/', load_areas, name='ajax_load_areas'),
    path('ajax/load-sub_familias/', load_sub_familias, name='ajax_load_sub_familias'),
    path('ajax/load1-levels1/', load1_levels1, name='ajax_load1_levels1'),
    path('ajax/load1-levels2/', load1_levels2, name='ajax_load1_levels2'),
    path('ajax/load1-levels3/', load1_levels3, name='ajax_load1_levels3'),
    path('ajax/load1-levels5/', load1_levels5, name='ajax_load1_levels5'),
    path('ajax/load1-levels7/', load1_levels7, name='ajax_load1_levels7'),
    path('ajax/load1-levels8/', load1_levels8, name='ajax_load1_levels8'),
    path('ajax/load-levels1/', load_levels1, name='ajax_load_levels1'),
    path('ajax/load-levels2/', load_levels2, name='ajax_load_levels2'),
    path('ajax/load-levels3/', load_levels3, name='ajax_load_levels3'),
    path('ajax/load-levels4/', load_levels4, name='ajax_load_levels4'),
    path('ajax/load-levels5/', load_levels5, name='ajax_load_levels5'),
    path('ajax/load-levels6/', load_levels6, name='ajax_load_levels6'),
    path('ajax/load-levels7/', load_levels7, name='ajax_load_levels7'),
    path('ajax/load-levels8/', load_levels8, name='ajax_load_levels8'),
    path('ajax/load-grade/', load_grade, name='ajax_load_grade'),
    path('ajax/load-detalhe/', load_detalhe, name='ajax_load_detalhe'),
    path('ajax/load-alteracao/', load_alteracao, name='ajax_load_alteracao'),
    path('ajax/load-exclusao/', load_exclusao, name='ajax_load_exclusao'),
    path("avaliacao-manual", mostra_pdf, name="avaliacao-manual"),
    path("avaliacao_rel_list/", AvaliacaoRelListView.as_view(), name="avaliacao-rel-list"),
    path("avaliacao_pdf/<int:pk>", AvaliacaoPdfListView.as_view(), name="avaliacao-pdf-list"),
    path("avaliacao_excel/", export_users_csv, name="avaliacao-excel-list"),
    path("avaliacao_excel/matriz", export_matriz_csv, name="avaliacao-excel-matriz"),
    path("avaliacao_rel_list_matriz/", AvaliacaoRelMatrizListView.as_view(), name="avaliacao-rel-list-matriz"),
    path("avaliacao_rel_list_hierarquica/", AvaliacaoRelHierarquicaListView.as_view(),
         name="avaliacao-rel-list-hierarquica"),

    path("avaliacao/<int:pk>", AvaliacaoPdfDetailView.as_view(), name="avaliacao-pdf"),


]

bluebox/urls.py
import django.views.static
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from user_account.views import *
from django.contrib.auth import views as auth_views
from django.urls import re_path


admin.site.site_header = " "
admin.site.index_title = "Administração BlueBox21"
#admin.site.site_title = "BlueBox21"-->


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', logar_usuario, name="logar_usuario"),
    path('logar_usuario', logar_usuario, name="logar_usuario"),
    path('index.html', index,name="index"),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_set.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="set_password.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"), name="password_reset_complete"),
    re_path(r"person/", include("person.urls")),
    re_path(r"customuser/", include("user_account.urls")),
    re_path(r"diretoria/", include("master.urls")),
    re_path(r"area/", include("master.urls")),
    re_path(r"tenant/", include("tenants.urls")),
    re_path(r"admin_descricao/", include("admin_descricao.urls")),
    re_path(r"descricao/", include("descricao.urls")),
    re_path(r"avaliacao/", include("avaliacao.urls")),
    re_path(r"api/", include("api.urls")),
]

descricao/urls.py
from django.urls import path

from api.views import TenantDocumentViewSet, DescricaoList
from .views import *

app_name = "descricao"


urlpatterns = [
    path("descricao_list/", DescricaoListView.as_view(), name="descricao-list"),
    path("descricao/create/", DescricaoCreateView.as_view(), name="descricao-create"),
    path("descricao/importar_dados/", ImportarDadosView.as_view(), name="descricao-create-lote"),
    path("descricao/createmodelo/<int:pk>", DescricaoModeloCreateView.as_view(), name="descricao-modelo-create"),
    path("descricao/update/<int:pk>", DescricaoUpdateView.as_view(), name="descricao-update"),
    path("descricao/delete/<int:pk>", DescricaoDeleteView.as_view(), name="descricao-delete"),
    path('ajax/load-areas/', load_areas, name='ajax_load_areas'),
    path('ajax/load-sub_familias/', load_sub_familias, name='ajax_load_sub_familias'),
    path("descricao/<int:pk>", DescricaoPdfDetailView.as_view(), name="descricao-pdf"),

    path("descricao/email/<str:title>/<str:email>", envia_email_acompanhamento, name="descricao-email"),

    path("descricao_rel_list/", DescricaoRelListView.as_view(), name="descricao-rel-list"),
    path("descricao_pdf/<int:pk>", DescricaoPdfListView.as_view(), name="descricao-pdf-list"),
    path("descricao_excel/", export_users_csv, name="descricao-excel-list"),
    # path("descricao_rel/descricao", TenantDocumentViewSet.as_view({"get": "list"}), name="descricao-rel"),
    path("descricao-manual", mostra_pdf, name="descricao-manual"),
    path("descricao_rel/descricao", DescricaoList.as_view({"get": "list"}), name="descricao-rel"),
    path("descricaomodelo_list/", DescricaomodeloListView.as_view(), name="descricaomodelo-list"),
    # path("tenants/<int:pk>/documents/", TenantDocumentViewSet.as_view({"get": "list"})),
    # path("document/", DocumentListView.as_view(), name="document-list"),
    path("descricao_list_aprovador/", DescricaoAprovadorListView.as_view(), name="descricao-list-aprovador"),
    path("descricao/update/aprovador/<int:pk>", DescricaoAprovadorUpdateView.as_view(), name="descricao-update-aprovador"),
    path("descricao_list_aprovacao/", DescricaoAprovacaoListView.as_view(), name="descricao-list-aprovacao"),
    path("descricao/update/aprovacao/<int:pk>", DescricaoAprovacaoUpdateView.as_view(), name="descricao-update-aprovacao"),
    path("descricao_aprovacao/<int:pk>", envia_aprovacao, name="descricao-aprovacao"),
    path("descricao_reprovacao/<int:pk>", envia_reprovacao, name="descricao-reprovacao"),
    path("descricao_list_aprovacao_final/", DescricaoAprovacaoFinalListView.as_view(), name="descricao-list-aprovacao-final"),
    path("descricao/update/aprovacao_final/<int:pk>", DescricaoAprovacaoFinalUpdateView.as_view(),
         name="descricao-update-aprovacao-final"),
    path('ajax/load-ia/', load_ia, name='ajax_load_ia'),
]

master/urls.py
from django.urls import path
from .views import *


app_name = "master"


urlpatterns = [
    path("diretoria_list/", DiretoriaListView.as_view(), name="diretoria-list"),
    path("diretoria/create/", DiretoriaCreateView.as_view(), name="diretoria-create"),
    path("diretoria/update/<int:pk>", DiretoriaUpdateView.as_view(), name="diretoria-update"),
    path("diretoria/delete/<int:pk>", DiretoriaDeleteView.as_view(), name="diretoria-delete"),
    path("area_list/", AreaListView.as_view(), name="area-list"),
    path("area/create/", AreaCreateView.as_view(), name="area-create"),
    path("area/update/<int:pk>", AreaUpdateView.as_view(), name="area-update"),
    path("area/delete/<int:pk>", AreaDeleteView.as_view(), name="area-delete"),
]

tenants/urls.py
from django.urls import path
from .views import *

app_name = "tenants"

urlpatterns = [
    path("tenant_list/", TenantListView.as_view(), name="tenant-list"),
    path("tenant/create/", TenantCreateView.as_view(), name="tenant-create"),
    path("tenant/update/<int:pk>", TenantUpdateView.as_view(), name="tenant-update"),
    path("delete/<int:pk>", TenantDeleteView.as_view(), name="tenant-delete"),

]

templates/index.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <title>BlueBox21</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-faded" style="background-color: #00205E">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent" >
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active" >
                        <a class="nav-link" href="/admin/">Admin</a>
                    </li>
                    <li class="nav-item active" >
                        <a class="nav-link"  href="#">Usuário Master <span class="sr-only">(current)</span></a>
                         <ul>
                             {% if request.user.kind == "Master" %}
                                 <li><a href="{% url 'tenants:tenant-list' %}">Empresa</a></li>
                                 <li><a href="{% url 'user_account:customuser-list' %}">Usuários</a></li>
                                 <li><a href="{% url 'master:diretoria-list' %}">Áreas da Empresa</a></li>
                                 <li><a href="{% url 'master:area-list' %}">Subáreas da Empresa</a></li>
                             {% endif %}
	       		         </ul>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Descrição de Cargos <span class="sr-only">(current)</span></a></a>
                        <ul>
<!--                            <li><a href="{% url 'admin_descricao:admin_descricao-list' %}">Modelos</a></li>-->
                            <li><a href="{% url 'descricao:descricao-list' %}">Descrição de Cargos</a></li>
                            {% if request.user.kind == "Master" %}
                                <li><a href="{% url 'descricao:descricao-list-aprovador' %}">Define Aprovador</a></li>
                            {% endif %}
                            <li><a href="{% url 'descricao:descricao-list-aprovacao' %}">Aprovação Pendente</a></li>
                            {% if request.user.kind == "Master" %}
                                <li><a href="{% url 'descricao:descricao-list-aprovacao-final' %}">Aprovação Final</a></li>
                                <li><a href="{% url 'descricao:descricao-rel-list' %}">Acompanhamento</a></li>
                            {% endif %}

<!--                            <li><a href="{% url 'descricao:descricao-rel' %}">Relatório2</a></li>-->
                            <li><a href="{% url 'descricao:descricao-manual' %}">Manual Elaboração</a></li>
                        </ul>
                    </li>

                    <li class="nav-item active">
                        <a class="nav-link" href="#">Avaliação de Cargo <span class="sr-only">(current)</span></a></a>
                        {% if request.user.kind == "Master" %}
                            <ul>
                                <li><a href="{% url 'descricao:descricaomodelo-list' %}">Com Descrição</a></li>
                                <li><a href="{% url 'avaliacao:avaliacao-list' %}">Sem Descrição</a></li>
                                <li><a href="{% url 'avaliacao:avaliacao-rel-list' %}">Visão Detalhada</a></li>
                                <li><a href="{% url 'avaliacao:avaliacao-rel-list-matriz' %}">Visão Matriz</a></li>
                                <li><a href="{% url 'avaliacao:avaliacao-rel-list-hierarquica' %}">Visão Hierárquica</a></li>
                                <li><a href="{% url 'avaliacao:avaliacao-manual' %}">Manual Avaliação</a></li>
                            </ul>
                        {% endif %}
                    </li>

<!--                    <li class="nav-item active">-->
<!--                        <a class="nav-link" href="#">Remuneração</a>-->
<!--                    </li>-->
<!--                    <li class="nav-item active">-->
<!--                        <a class="nav-link" href="#">Práticas</a>-->
<!--                    </li>-->
<!--                    <li class="nav-item active">-->
<!--                        <a class="nav-link" href="#">Relatórios</a>-->
<!--                    </li>-->
                    <li class="nav-item active">
                       <a class="nav-link" href="logar_usuario"><font size="1"><u>Sair </u></font><span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#"><font size="1"><u>{{ request.user.name }} - {{request.user.kind}}</u></font></a>
                    </li>



                </ul>
            </div>
        </div>

    </nav>

    <div class="container">
        <div class="jumbotron">
            <img src="{% static 'img/logo_h.png' %}" alt="logo" width="380px">
             <hr class="my-4">
            <p class="lead"  style="color: #00205E">A sua Plataforma Web para Gestão de Cargos e Salários.</p>
            </br>
            </br>

<!--            <a id="add-link" href="{% url 'descricao:descricao-list' %}">-->
<!--                <div class="col-2 add-div">-->
<!--                    <i class="fas fa-plus"></i>  Descrição de Cargo-->
<!--                </div>-->
<!--            </a>-->

            </br>
            <div class="container dashboard">
                <div class="col-4 dashboard-box" id="dashboard-descricoes">
                    <a id="add-link" href="{% url 'descricao:descricao-list' %}">
                        <h4 style="color:#FFFFFF"> Descrições Cadastradas</h4>
                    </a>
                    <span>{{descricao}}</span>
                </div>
            </div>

            <div class="container dashboard">
                <div class="col-4 dashboard-box" id="dashboard-avaliacoes">
                    <a id="add-link2" href="{% url 'avaliacao:avaliacao-list' %}">
                        <h4 style="color:#FFFFFF"> Avaliações Realizadas</h4>
                    </a>
                    <span>{{avaliacao}}</span>
                </div>
            </div>

            <div class="container dashboard">
                <div class="col-4 dashboard-box" id="dashboard-pendentes">
                    <a id="add-link3" href="{% url 'descricao:descricao-list-aprovacao' %}">
                        <h4 style="color:#FFFFFF"> Descrições Pendentes</h4>
                    </a>
                    <span>{{pendente}}</span>
                </div>
            </div>
            </br>
            </br>
            </br>
            </br>
            </br>
            </br>
        </div>
    </div>


</body>

</html>

templates/login.html
<!DOCTYPE html>

{% load static %}

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fa/css/all.min.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <title>BlueBox21</title>
    <style>
        .container {
        width: 100vw;
        height: 100vh;
        display: flex;
        flex-direction: row;
        justify-content: center;
        align-items: center
        }
        .box {
        width: 300px;
        height: 300px;
        background: #fff;
        }
        body {
        margin: 0px;
        }
    </style>
</head>

<body>
<div class="container">
    <form method="post">
        {% csrf_token %}
        <div class="container mt-6">
            <div class="row">
                <div class="col-25">
                    <h2 style="color:#00205E">  <p> <center> Acesso ao Sistema </center> </h2></br>
                        <img src="{% static 'img/logo_h.png' %}" alt="logo" width="300px"></p> </br>
                    <form>
                        <div class="form-group">
                            {{form_login.username.errors}}
                            <label style="color:#00205E">Email  :  </label>
                            {{form_login.username}}
                        </div>
                        <div class="form-group">
                            {{form_login.password.errors}}
                            <label style="color:#00205E">Senha: </label>
                            {{form_login.password}}
                        </div>
                        </br>
                        <button type="submit" class="btn btn-primary">Enviar</button>

                        <p></br><a href="reset_password/"><FONT SIZE=-2><font color="#00205E"><u>Esqueci a Senha.</u></font></FONT></a> </p>
                        <a href="reset_password/"><FONT SIZE=-2><font color="#00205E"><u>Crie ou Altere a sua senha.</u></font></FONT></a>

                    </form>
                </div>
            </div>
        </div>
    </form>
<div class="box">
</div>
</div>
</body>
</html>

templates/password_reset.html
<!DOCTYPE html>

<html lang="pt-br" >
<head>
<title>Recuperar senha</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">

<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">



    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">


<meta name="robots" content="NONE,NOARCHIVE">
</head>


<body class=""
  data-admin-utc-offset="-10800">

<!-- Container -->
<div id="container">


    <!-- Header -->
    <div id="header">
        <div id="branding">

<h1 id="site-name"><a>Administração Bluebox</a></h1>

        </div>




    </div>
    <!-- END Header -->

<div class="breadcrumbs">
<!--<a href="/admin/">Início</a>-->
&rsaquo; Recuperar senha
</div>



    <div class="main shifted" id="main">

      <div class="content">



        <!-- Content -->
        <div id="content" class="colM">

          <h1>Recuperar senha</h1>


<p>Esqueceu sua senha? Forneça seu endereço de email abaixo, e nós te enviaremos um email com instruções para configurar uma nova.</p>

<form method="post"><input type="hidden" name="csrfmiddlewaretoken" value="YMOe1z4kIyW0sZKFJxrvEa1q3FRxIesaYUFHTcp15Ez1EAiNiJc4fn24tf27uJld">
<fieldset class="module aligned">
    <div class="form-row field-email">
        {% csrf_token %}
        <label for="id_email">Endereço de email:</label>
        <input type="email" name="email" autocomplete="email" maxlength="254" required id="id_email">
    </div>
    <input type="submit" value="Reinicializar minha senha">
</fieldset>
</form>



          <br class="clear">
        </div>
        <!-- END Content -->
        <div id="footer"></div>
      </div>
    </div>
</div>
<!-- END Container -->
</body>
</html>

templates/reset_password_complete.html
<!DOCTYPE html>

<html lang="pt-br" >
<head>
<title>Redefinição de senha completa</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">





    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">


<meta name="robots" content="NONE,NOARCHIVE">
</head>


<body class=""
  data-admin-utc-offset="-10800">

<!-- Container -->
<div id="container">


    <!-- Header -->
    <div id="header">
        <div id="branding">

<h1 id="site-name"><a>Administração Bluebox</a></h1>

        </div>




    </div>
    <!-- END Header -->

<div class="breadcrumbs">
<!--<a href="/admin/">Início</a>-->
&rsaquo; Recuperar senha

</div>



    <div class="main shifted" id="main">

      <div class="content">



        <!-- Content -->
        <div id="content" class="colM">

          <h1>Redefinição de senha completa</h1>


<p>Sua senha foi definida. Você pode prosseguir e se autenticar agora.</p>

            <p><a href="/logar_usuario"><b><u>Acessar</u></b></a></p>



          <br class="clear">
        </div>
        <!-- END Content -->
        <div id="footer"></div>
      </div>
    </div>
</div>
<!-- END Container -->
</body>
</html>

templates/reset_password_set.html
<!DOCTYPE html>

<html lang="pt-br" >
<head>
<title>Redefinição de senha enviada</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">





    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">


<meta name="robots" content="NONE,NOARCHIVE">
</head>


<body class=""
  data-admin-utc-offset="-10800">

<!-- Container -->
<div id="container">


    <!-- Header -->
    <div id="header">
        <div id="branding">

<h1 id="site-name"><a>Administração Bluebox</a></h1>

        </div>




    </div>
    <!-- END Header -->

<div class="breadcrumbs">
<!--<a href="/admin/">Início</a>-->
&rsaquo; Recuperar senha
</div>



    <div class="main shifted" id="main">

      <div class="content">



        <!-- Content -->
        <div id="content" class="colM">

          <h1>Redefinição de senha enviada</h1>


<p>Nos te enviamos um email com instruções para configurar sua senha, se uma conta existe com o email fornecido. Você receberá a mensagem em breve.</p>

<p>Se você não recebeu um email, por favor certifique-se que você forneceu o endereço que você está cadastrado, e verifique sua pasta de spam.</p>



          <br class="clear">
        </div>
        <!-- END Content -->
        <div id="footer"></div>
      </div>
    </div>
</div>
<!-- END Container -->
</body>
</html>

templates/set_password.html
<!DOCTYPE html>

<html lang="pt-br" >
<head>
<title>Digite a nova senha</title>
<link rel="stylesheet" type="text/css" href="/static/admin/css/base.css">

<link rel="stylesheet" type="text/css" href="/static/admin/css/forms.css">



    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <link rel="stylesheet" type="text/css" href="/static/admin/css/responsive.css">


<meta name="robots" content="NONE,NOARCHIVE">
</head>


<body class=""
  data-admin-utc-offset="-10800">

<!-- Container -->
<div id="container">


    <!-- Header -->
    <div id="header">
        <div id="branding">

<h1 id="site-name"><a>Administração Bluebox</a></h1>

        </div>




    </div>
    <!-- END Header -->

<div class="breadcrumbs">
<!--<a href="/admin/">Início</a>-->
&rsaquo; Confirmação de recuperação de senha
</div>



    <div class="main shifted" id="main">

      <div class="content">



        <!-- Content -->
        <div id="content" class="colM">

          <h1>Digite a nova senha</h1>




<p>Por favor, informe sua nova senha duas vezes para que possamos verificar se você a digitou corretamente.</p>

<form method="post"><input type="hidden" name="csrfmiddlewaretoken" value="lYoC2TzgxtvTFSDuxuZk5jp4lyBFFMZAZKScsATNbJXucgrfrQVhB3QGCq1xbsVc">
    {% csrf_token %}
<fieldset class="module aligned">
    <div class="form-row field-password1">

        <label for="id_new_password1">Nova senha:</label>
        <input type="password" name="new_password1" autocomplete="new-password" required id="id_new_password1">
    </div>
    <div class="form-row field-password2">

        <label for="id_new_password2">Confirme a senha:</label>
        <input type="password" name="new_password2" autocomplete="new-password" required id="id_new_password2">
    </div>
    <input type="submit" value="Alterar minha senha">
</fieldset>
</form>





          <br class="clear">
        </div>
        <!-- END Content -->
        <div id="footer"></div>
      </div>
    </div>
</div>
<!-- END Container -->
</body>
</html>