api/urls.py
from django.urls import path
from .views import *


app_name = "api"


urlpatterns = [
    path("descricao_rel/descricao", TenantDocumentViewSet.as_view({"get": "list"})),

]

bluebox/urls.py
import django.views.static
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from user_account.views import *
from django.contrib.auth import views as auth_views
from django.urls import re_path


admin.site.site_header = " "
admin.site.index_title = "Administração BlueBox21"
#admin.site.site_title = "BlueBox21"-->


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', logar_usuario, name="logar_usuario"),
    path('logar_usuario', logar_usuario, name="logar_usuario"),
    path('index.html', index,name="index"),
    path('reset_password/', auth_views.PasswordResetView.as_view(template_name="password_reset.html"), name="reset_password"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name="reset_password_set.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name="set_password.html"), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name="reset_password_complete.html"), name="password_reset_complete"),
    re_path(r"person/", include("person.urls")),
    re_path(r"customuser/", include("user_account.urls")),
    re_path(r"diretoria/", include("master.urls")),
    re_path(r"area/", include("master.urls")),
    re_path(r"tenant/", include("tenants.urls")),
    re_path(r"admin_descricao/", include("admin_descricao.urls")),
    re_path(r"descricao/", include("descricao.urls")),
    re_path(r"avaliacao/", include("avaliacao.urls")),
    re_path(r"api/", include("api.urls")),
]

master/urls.py
from django.urls import path
from .views import *


app_name = "master"


urlpatterns = [
    path("diretoria_list/", DiretoriaListView.as_view(), name="diretoria-list"),
    path("diretoria/create/", DiretoriaCreateView.as_view(), name="diretoria-create"),
    path("diretoria/update/<int:pk>", DiretoriaUpdateView.as_view(), name="diretoria-update"),
    path("diretoria/delete/<int:pk>", DiretoriaDeleteView.as_view(), name="diretoria-delete"),
    path("area_list/", AreaListView.as_view(), name="area-list"),
    path("area/create/", AreaCreateView.as_view(), name="area-create"),
    path("area/update/<int:pk>", AreaUpdateView.as_view(), name="area-update"),
    path("area/delete/<int:pk>", AreaDeleteView.as_view(), name="area-delete"),
]

master/models.py
from django.db import models

from tenants.models import TenantAwareModel


class Diretoria(TenantAwareModel):

    name = models.CharField(max_length=255, verbose_name='Nome', null=False, default="")
    is_active = models.BooleanField(default=True, verbose_name='Ativo')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        ordering = ["name"]
        unique_together = ('name', 'tenant_id',)
        verbose_name = 'Area da Empresa'
        verbose_name_plural = 'Áreas da Empresa'


class Area(TenantAwareModel):

    board = models.ForeignKey(Diretoria, on_delete=models.PROTECT, verbose_name='Área da Empresa')
    name = models.CharField(max_length=255, verbose_name='Subárea da Empresa', null=False, default="")
    is_active = models.BooleanField(default=True, verbose_name='Ativo')

    def __str__(self):
        return f"{self.name}"

    class Meta:
        ordering = ["name"]
        unique_together = ('name', 'board', 'tenant')
        verbose_name = 'Subárea da Empresa'
        verbose_name_plural = 'Subáreas da Empresa'

master/forms.py
from django import forms
from .models import *
from master.models import Diretoria


class DiretoriaForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'required': 'true'}), label="Nome")
    tenant_id = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'required': 'true'}), label="tenant_id")
    is_active = forms.BooleanField()

    class Meta:
        model = Diretoria
        fields = ['name', 'tenant_id', 'is_active']


class AreaForm(forms.ModelForm):

    class Meta:
        model = Area
        fields = ['name', 'board', 'is_active']

# Filtrar a dropdow
    def __init__(self, *args, **kwargs):
        tenant_id = kwargs.pop('tenant_id', None)
        super(AreaForm, self).__init__(*args, **kwargs)
        self.fields['board'].queryset = Diretoria.objects.filter(tenant_id=tenant_id)

master/views.py
from django.db.models import ProtectedError
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import DeleteView, CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages

from tenants.utils import tenant_from_request
from .forms import AreaForm
from .models import Diretoria, Area


class DiretoriaDetailView(LoginRequiredMixin, DetailView):
    model = Diretoria
    context_object_name = "diretoria"


class DiretoriaListView(LoginRequiredMixin, ListView):
    model = Diretoria
    context_object_name = "diretoria"

    def get_queryset(self):
        tenant_id = tenant_from_request(self.request)
        return super().get_queryset().filter(tenant_id=tenant_id).all()


class DiretoriaDeleteView(LoginRequiredMixin, DeleteView):
    model = Diretoria
    context_object_name = "diretoria"
    success_url = reverse_lazy("master:diretoria-list")

    def delete(self, request, *args, **kwargs):

        """
        Call the delete() method on the fetched object and then redirect to the
        success URL. If the object is protected, send an error message.
        """
        self.object = self.get_object()

        try:
            self.object.delete()
        except ProtectedError:
            messages.add_message(request, messages.ERROR, 'Can not delete: this parent has a child!')
            return redirect('master:diretoria-list') # The url of the delete view (or whatever you want)

        return HttpResponseRedirect(reverse_lazy("master:diretoria-list"))

    # def delete(self, request, *args, **kwargs):
    #     object = self.get_object()
    #     if object.children.count() > 0:
    #         messages.add_message(request, messages.ERROR, "Can't be deleted, has childern")
    #         return redirect('master:diretoria-list')
    #     return super().delete(request, *args, **kwargs)


class DiretoriaCreateView(LoginRequiredMixin, CreateView):
    model = Diretoria
    fields = ['name', 'is_active']  # preencher todos os da views.py
    success_url = reverse_lazy("master:diretoria-list")

    # Forçar o preencimento do tenant_id com o tenant_id do usuario logado
    def form_valid(self, form):
        tenant_id = tenant_from_request(self.request)
        form.instance.tenant_id = tenant_id

        self.object = form.save()

        return super(DiretoriaCreateView, self).form_valid(form)


class DiretoriaUpdateView(LoginRequiredMixin, UpdateView):
    model = Diretoria
    fields = ['name', 'tenant', 'is_active']  # preencher todos os da views.py
    success_url = reverse_lazy("master:diretoria-list")


class AreaDetailView(LoginRequiredMixin, DetailView):
    model = Diretoria
    context_object_name = "area"


class AreaListView(LoginRequiredMixin, ListView):
    model = Area
    context_object_name = "area"

    def get_queryset(self):
        tenant_id = tenant_from_request(self.request)
        return super().get_queryset().filter(tenant_id=tenant_id).all()


class AreaDeleteView(LoginRequiredMixin, DeleteView):
    model = Area
    context_object_name = "area"
    success_url = reverse_lazy("master:area-list")

    def delete(self, request, *args, **kwargs):

        """
        Call the delete() method on the fetched object and then redirect to the
        success URL. If the object is protected, send an error message.
        """
        self.object = self.get_object()

        try:
            self.object.delete()
        except ProtectedError:
            messages.add_message(request, messages.ERROR, 'Can not delete: this parent has a child!')
            return redirect('master:area-list') # The url of the delete view (or whatever you want)

        return HttpResponseRedirect(reverse_lazy("master:area-list"))


class AreaCreateView(LoginRequiredMixin, CreateView):
    model = Area
    form_class = AreaForm
    success_url = reverse_lazy("master:area-list")

# Forçar o preencimento do tenant_id com o tenant_id do usuario logado
    def form_valid(self, form):
        tenant_id = tenant_from_request(self.request)
        form.instance.tenant_id = tenant_id

        self.object = form.save()

        return super(AreaCreateView, self).form_valid(form)

# pegar o tenant do usuario logado para filtrar a dropdonw
    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(AreaCreateView, self).get_form_kwargs()
        tenant_id = tenant_from_request(self.request)
        kwargs['tenant_id'] = tenant_id
        return kwargs


class AreaUpdateView(LoginRequiredMixin, UpdateView):
    model = Area
    form_class = AreaForm
    success_url = reverse_lazy("master:area-list")

    # pegar o tenant do usuario logado para filtrar a dropdonw
    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(AreaUpdateView, self).get_form_kwargs()
        tenant_id = tenant_from_request(self.request)
        kwargs['tenant_id'] = tenant_id
        return kwargs

master/templates/master/area_confirm_delete.html
{% extends 'base.html' %}

{% block conteudo_painel %}
    <h2>Exclusão de Subáreas da Empresa</h2>
    <br>
    <form method="post">{% csrf_token %}
        <p>Tem certeza que deseja apagar?</p>
        <button type="submit" class="btn btn-danger" data-toggle="tooltip" data-placement="top"
                title="Cuidado! Essa operação não pode ser desfeita!">Confirmar
        </button>
        <a href="{% url 'master:area-list' %}"><button type="button" class="btn btn-secondary">Cancelar</button></a>
    </form>
{% endblock %}

master/templates/master/area_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo_painel %}
   Cadastro da Subárea da Empresa
{% endblock titulo_painel %}

{% block conteudo_painel %}
<form method="post" autocomplete="off" enctype="multipart/form-data">{% csrf_token %}
    <div class="row">
        <div class="col-md-4">
            {{ form.board|as_crispy_field }}
            <br>
            {{ form.name|as_crispy_field }}
            <br>
        </div>
        <div class="col-md-2">
            {{ form.is_active|as_crispy_field }}
            <br>
        </div>
    </div>
    <br>
    <button type="submit" class="btn btn-success">Salvar</button>
    <a href="{% url 'master:area-list' %}"><button type="button" class="btn btn-secondary">Cancelar</button></a>

</form>
{% endblock %}

master/templates/master/area_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo_painel %}
    Lista de Subáreas da Empresa
{% endblock titulo_painel %}

{% block conteudo_painel %}

    <a id="add-link" href="{% url 'master:area-create' %}">
        <div class="col-2 add-div">
            <i class="fas fa-plus"></i> Adicionar Subárea da Empresa
        </div>
    </a>
    <br>

    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12">
                <table id="table_id" class="display" align="center" style="width:100%">
                    <thead>
                        <tr>
                            <th><center>Código</center></th>
                            <th><center>Áreas da Empresa</center></th>
                            <th><center>Código</center></th>
                            <th><center>Subárea da Empresa</center></th>
                            <th><center>Editar</center></th>
                            <th><center>Excluir</center></th>
                        </tr>
                    </thead>
                    <tbody>
                    {%for area in object_list %}
                        <tr>
                            <td><center>{{area.board_id}}</center></td>
                            <td>{{area.board}}</td>
                            <td><center>{{area.id}}</center></td>
                            <td>{{area.name}}</td>
                            <td><a href="{% url 'master:area-update' area.id %}"><center><i class="fas fa-edit"></i></center></a></td>
                            <td><a href="{% url 'master:area-delete' area.id %}"><center><i class="far fa-trash-alt"></i></center></a></td>
                        </tr>
                     {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
         <a href="/index.html"><button type="button" class="btn btn-secondary">Voltar</button></a>
    </form>

{% endblock conteudo_painel %}

{% block js %}
<script>
    $(document).ready( function () {
        $('#table_id').DataTable();
    } );
    $('#table_id').DataTable({
        columnDefs: [ {
                targets: [ 0 ],
                orderData: [ 0, 1 ]
            } ]
    } );
</script>
{% endblock js %}

master/templates/master/diretoria_confirm_delete.html
{% extends 'base.html' %}

{% block conteudo_painel %}
    <h2>Exclusão de Áreas da Empresa</h2>
    <br>
    <form method="post">{% csrf_token %}
        <p>Tem certeza que deseja apagar?</p>
        <button type="submit" class="btn btn-danger" data-toggle="tooltip" data-placement="top"
                title="Cuidado! Essa operação não pode ser desfeita!">Confirmar
        </button>
        <a href="{% url 'master:diretoria-list' %}"><button type="button" class="btn btn-secondary">Cancelar</button></a>
    </form>
{% endblock %}

master/templates/master/diretoria_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo_painel %}
   Cadastro da Área da Empresa
{% endblock titulo_painel %}

{% block conteudo_painel %}
<form method="post" autocomplete="off" enctype="multipart/form-data">{% csrf_token %}
    <div class="row">
        <div class="col-md-4">
            {{ form.name|as_crispy_field }}
            <br>
        </div>
        <div class="col-md-2">
            {{ form.is_active|as_crispy_field }}
            <br>
        </div>
    </div>
    <br>
    <button type="submit" class="btn btn-success">Salvar</button>
    <a href="{% url 'master:diretoria-list' %}"><button type="button" class="btn btn-secondary">Cancelar</button></a>

</form>
{% endblock %}

master/templates/master/diretoria_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titulo_painel %}
    Lista de Áreas da Empresa
{% endblock titulo_painel %}

{% block conteudo_painel %}

    <a id="add-link" href="{% url 'master:diretoria-create' %}">
        <div class="col-2 add-div">
            <i class="fas fa-plus"></i> Adicionar Áreas da Empresa
        </div>
    </a>
    <br>

    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-12">
                <table id="table_id" class="display" align="center" style="width:100%">
                    <thead>
                        <tr>
                            <th><center>Código</center></th>
                            <th><center>Áreas da Empresa</center></th>
                            <th><center>Editar</center></th>
                            <th><center>Excluir</center></th>
                        </tr>
                    </thead>
                    <tbody>
                    {%for diretoria in object_list %}
                        <tr>
                            <td><center>{{diretoria.id}}</center></td>
                            <td>{{diretoria.name}}</td>
                            <td><a href="{% url 'master:diretoria-update' diretoria.id %}"><center><i class="fas fa-edit"></i></center></a></td>
                            <td><a href="{% url 'master:diretoria-delete' diretoria.id %}"><center><i class="far fa-trash-alt"></i></center></a></td>
                        </tr>
                     {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <br>
         <a href="/index.html"><button type="button" class="btn btn-secondary">Voltar</button></a>
    </form>

{% endblock conteudo_painel %}

{% block js %}
<script>
    $(document).ready( function () {
        $('#table_id').DataTable();
    } );
</script>
{% endblock js %}